### ISSUE TITLE
Aktivitäts- und Ressourcenform fehlerhaft durch geolocation

### ISSUE THREAD

**Issue by relecand** [jojoob/moodle-availability_geolocation#6]
Wenn Geolocation-Voraussetzung installiert, aber kein Block "Geolocation" in einem Kurs existiert, dann wird kein Aktivitäts-oder Ressourcenform aufgerufen. Folgende Fehlermeldung:

Datensatz kann nicht in der Datenbanktabelle block_instances gefunden werden

Weitere Informationen über diesen Fehler
Debug info: SELECT id,parentcontextid FROM {block_instances} WHERE id IS NULL
[array (
)]
Error code: invalidrecord
Stack trace:

    line 1451 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
    line 1427 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
    line 7322 of /lib/accesslib.php: call to moodle_database->get_record()
    line 432 of /blocks/moodleblock.class.php: call to context_block::instance()
    line 1667 of /lib/blocklib.php: call to block_base->_load_instance()
    line 36 of /availability/condition/geolocation/classes/frontend.php: call to block_instance()
    line 120 of /availability/classes/frontend.php: call to availability_geolocation\frontend->__construct()
    line 455 of /course/moodleform_mod.php: call to core_availability\frontend::include_all_javascript()
    line 140 of /mod/glossary/mod_form.php: call to moodleform_mod->standard_coursemodule_elements()
    line 191 of /lib/formslib.php: call to mod_glossary_mod_form->definition()
    line 86 of /course/moodleform_mod.php: call to moodleform->moodleform()
    line 252 of /course/modedit.php: call to moodleform_mod->moodleform_mod()

Output buffer: <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/moodle26/blocks/moodleblock.class.php</b> on line <b>432</b><br />

**Comment by jojoob** [comment]
Notwendigkeit eines Checks ob geolocation block vorhanden bevor ein hinzufügen der condition erlaubt wird.
